msisdn:
  local:
    country_code: "+216"
    ndc_ranges:
      - [30, 35]
      - [50, 55]
    digits: 6
    count: 10
  national:
    country_code: "+216"
    ndc_ranges:
      - [20, 29]
      - [90, 99]
    digits: 6
    count: 10
  international:
    prefixes:
      - "+2126"
      - "+336"
      - "+441"
      - "+491"
    digits: 8
    count: 10
