measures:
  - mesure_name: "Total Reel"
    mesure_type: "SUM"
    table_name: "reel"
    column_name: "reel"
    mesure_format: "### ### ### $"
  - mesure_name: "Total Reel over 4years"
    mesure_type: "SUM4FY"
    table_name: "reel"
    column_name: "reel"
  - mesure_name: "Total Budget over 4years"
    mesure_type: "SUM4FY"
    table_name: "budget_prevision"
    column_name: "budget"
  - mesure_name: "Total Prevision over 4years"
    mesure_type: "SUM4FY"
    table_name: "budget_prevision"
    column_name: "prevision"
  - mesure_name: "Total Reel AEC"
    mesure_type: "SUMCFY"
    table_name: "reel"
    column_name: "reel"
  - mesure_name: "AEC vs budget"
    mesure_type: "CFYVS"
    table_name1: "reel"
    column_name1: "reel"
    table_name1: "budget_prevision"
    column_name1: "budget"
  - mesure_name: "AEC vs prevision"
    mesure_type: "CFYVS"
    table_name1: "reel"
    column_name1: "reel"
    table_name2: "budget_prevision"
    column_name2: "prevision"
  - mesure_name: "Monthly reel vs budget"
    mesure_type: "CFYVS"
    table_name1: "reel"
    column_name1: "reel"
    table_name1: "budget_prevision"
    column_name1: "budget"
  - mesure_name: "Monthly reel vs prevision"
    mesure_type: "CMVS"
    table_name1: "reel"
    column_name1: "reel"
    table_name2: "budget_prevision"
    column_name2: "prevision"


    