calendar:
  calendar_table_name: "CalendrierFinancier"
  calendar_column_name: "Date"
  calendar_start_date: "2020-01-01"
  calendar_end_date: "2025-12-31"
  generate: true
  
mesures:
  - mesure_name: "Total Reel over 4years"
    mesure_type: "SUMFYRW"
    table_name: "reel"
    column_name: "reel"
  - mesure_name: "Total Budget over 4years"
    mesure_type: "SUMFYRW"
    table_name: "budget_prevision"
    column_name: "budget"
  - mesure_name: "Total Prevision over 4years"
    mesure_type: "SUMFYRW"
    table_name: "budget_prevision"
    column_name: "prevision"
  - mesure_name: "Total Reel AEC"
    mesure_type: "SUMFYOY"
    table_name: "reel"
    column_name: "reel"
    year_offset: 0
  - mesure_name: "Total Budget AEC"
    mesure_type: "SUMFYOY"
    table_name: "budget_prevision"
    column_name: "budget"
    year_offset: 0
  - mesure_name: "Total Budget AEC"
    mesure_type: "SUMFYOY"
    table_name: "budget_prevision"
    column_name: "prevision"
    year_offset: 0
  - mesure_name: "Total Reel AEC vs LY"
    mesure_type: "YOYFYCR"
    table_name: "reel"
    column_name: "reel"
    year_offset: 0