
Total Reel over 4years = 
VAR _start_date = DATE(YEAR(TODAY()) - 3, 4, 1)  
VAR _end_date = 
    IF(
        MONTH(TODAY()) > 4 - 1,  
        DATE(YEAR(TODAY()) + 1, 3, 31),  
        DATE(YEAR(TODAY()), 3, 31)  
    )
RETURN
    CALCULATE(
        SUM(reel[reel]),  
        FILTER(
            dimCalendrier,
            dimCalendrier[Date] >= _start_date 
            && dimCalendrier[Date] <= _end_date
        )
    )


Total Budget over 4years = 
VAR _start_date = DATE(YEAR(TODAY()) - 3, 4, 1)  
VAR _end_date = 
    IF(
        MONTH(TODAY()) > 4 - 1,  
        DATE(YEAR(TODAY()) + 1, 3, 31),  
        DATE(YEAR(TODAY()), 3, 31)  
    )
RETURN
    CALCULATE(
        SUM(budget_prevision[budget]),  
        FILTER(
            dimCalendrier,
            dimCalendrier[Date] >= _start_date 
            && dimCalendrier[Date] <= _end_date
        )
    )


Total Prevision over 4years = 
VAR _start_date = DATE(YEAR(TODAY()) - 3, 4, 1)  
VAR _end_date = 
    IF(
        MONTH(TODAY()) > 4 - 1,  
        DATE(YEAR(TODAY()) + 1, 3, 31),  
        DATE(YEAR(TODAY()), 3, 31)  
    )
RETURN
    CALCULATE(
        SUM(budget_prevision[prevision]),  
        FILTER(
            dimCalendrier,
            dimCalendrier[Date] >= _start_date 
            && dimCalendrier[Date] <= _end_date
        )
    )


Total Reel AEC = 
VAR _year_offset = 0  
VAR _start_date = 
    DATE(
        YEAR(TODAY()) - _year_offset - IF(MONTH(TODAY()) < 4, 1, 0), 
        4, 
        1
    )  
VAR _end_date = 
    DATE(
        YEAR(TODAY()) - _year_offset + IF(MONTH(TODAY()) >= 4, 1, 0), 
        3, 
        31
    )  
RETURN
    CALCULATE(
        SUM(reel[reel]),
        FILTER(
            dimCalendrier,
            dimCalendrier[Date] >= _start_date &&
            dimCalendrier[Date] <= _end_date
        )
    )


Total Budget AEC = 
VAR _year_offset = 0  
VAR _start_date = 
    DATE(
        YEAR(TODAY()) - _year_offset - IF(MONTH(TODAY()) < 4, 1, 0), 
        4, 
        1
    )  
VAR _end_date = 
    DATE(
        YEAR(TODAY()) - _year_offset + IF(MONTH(TODAY()) >= 4, 1, 0), 
        3, 
        31
    )  
RETURN
    CALCULATE(
        SUM(budget_prevision[budget]),
        FILTER(
            dimCalendrier,
            dimCalendrier[Date] >= _start_date &&
            dimCalendrier[Date] <= _end_date
        )
    )


Total Budget AEC = 
VAR _year_offset = 0  
VAR _start_date = 
    DATE(
        YEAR(TODAY()) - _year_offset - IF(MONTH(TODAY()) < 4, 1, 0), 
        4, 
        1
    )  
VAR _end_date = 
    DATE(
        YEAR(TODAY()) - _year_offset + IF(MONTH(TODAY()) >= 4, 1, 0), 
        3, 
        31
    )  
RETURN
    CALCULATE(
        SUM(budget_prevision[prevision]),
        FILTER(
            dimCalendrier,
            dimCalendrier[Date] >= _start_date &&
            dimCalendrier[Date] <= _end_date
        )
    )


Total Reel AEC vs LY = 
VAR _year_offset = 0
VAR _year_0 = 
    CALCULATE(
        SUM(reel[reel]),
        FILTER(
            dimCalendrier,
            dimCalendrier[Date] >= DATE(
                YEAR(TODAY()) - _year_offset - IF(MONTH(TODAY()) < 4, 1, 0), 
                4, 
                1
            ) &&
            dimCalendrier[Date] <= DATE(
                YEAR(TODAY()) - _year_offset + IF(MONTH(TODAY()) >= 4, 1, 0), 
                3, 
                31
            )
        )
    )
VAR _year_1 = 
    CALCULATE(
        SUM(reel[reel]),
        FILTER(
            dimCalendrier,
            dimCalendrier[Date] >= DATE(
                YEAR(TODAY()) - (_year_offset + 1) - IF(MONTH(TODAY()) < 4, 1, 0), 
                4, 
                1
            ) &&
            dimCalendrier[Date] <= DATE(
                YEAR(TODAY()) - (_year_offset + 1) + IF(MONTH(TODAY()) >= 4, 1, 0), 
                3, 
                31
            )
        )
    )
RETURN
    _year_0 - _year_1
