
CalendrierFinancier = 
ADDCOLUMNS(
    CALENDAR(DATE(2020, 1, 1), DATE(2025, 12, 31)),
    "AnneeFinanciere", 
        VAR _AnneeFinanciere = 
            IF (
                MONTH([Date]) >= 4, 
                RIGHT(YEAR([Date]), 2) & RIGHT(YEAR([Date]) + 1, 2),
                RIGHT(YEAR([Date]) - 1, 2) & RIGHT(YEAR([Date]), 2)
            )
    RETURN _AnneeFinanciere,
    "AnneeMois", 
        VAR _AnneeMois = FORMAT([Date], "YYYY") & "-" & FORMAT([Date], "MM")
        RETURN _AnneeMois,
    "Mois", 
        SWITCH(
            TRUE(),
            MONTH([Date]) = 1, "JAN",
            MONTH([Date]) = 2, "FEV",
            MONTH([Date]) = 3, "MAR",
            MONTH([Date]) = 4, "AVR",
            MONTH([Date]) = 5, "MAI",
            MONTH([Date]) = 6, "JUN",
            MONTH([Date]) = 7, "JUI",
            MONTH([Date]) = 8, "AOU",
            MONTH([Date]) = 9, "SEP",
            MONTH([Date]) = 10, "OCT",
            MONTH([Date]) = 11, "NOV",
            MONTH([Date]) = 12, "DEC",
            BLANK()
        )
)
