columns:
  - name: calling_party_number
    type: msisdn
    msisdn:
      country_code: 216
      network_code:
        values: ['123', '456', '789']
      subscriber_number:
        values: ['1234567', '9876543210']
      format: '+%country_code% %network_code% %subscriber_number%'
  - name: called_party
    type: msisdn
    msisdn:
      country_code: 
        values: ['1', '44', '91']
      network_code:
        values: ['123', '456', '789']
      subscriber_number:
        values: ['7654321', '1098765432']
      format: '+%country_code% %network_code% %subscriber_number%'

columns:
  - name: calling_party_number
    type: msisdn
    msisdn:
      country_code: 216
      format: '+%country_code%'
  - name: called_party_number
    type: msisdn
    msisdn:
      country_code: [216,212]
      format: '+%country_code%'